project:
  type: website
  output-dir: docs

website:
  title: "PHYS 308 Fall 2024"
  navbar:
    background: primary #color of background is primary color in palette
    search: true
    #left is left-aligned top bar
    left:
      - href: index.qmd
        text: Home
      - href: https://phys308.github.io/
        text: "Course Description"
        target: _blank #makes it open in new page
      - href: https://docs.google.com/spreadsheets/d/12bIFUWPCjQ1M-Uhela3GO7mmHF07_UZhAoRJAUmq4t4/edit?usp=sharing
        text: "Schedule" 
        target: _blank #makes it open in new page
      - sidebar:syllabus
      - sidebar:coursecontent
            
  sidebar:
    - id: syllabus
      title: "Syllabus and FAQ"
      style: "docked"
      background: light
      contents:
       - starthere.qmd
       - syllabus.qmd
       - FAQ.qmd

   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

